### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by juler69** [adfinis-sygroup/pyark#15]
Hi there,

I have extended this module quite a bit and also altered the way it works - I don't use argparse in my version.  Is there a way I can share the code I have written without using a pull request - you might not want (or like) all the changes I've made.  I don't really do this very often so I'm a bit unsure how to proceed.

Jonathan

**Comment by tongpu** [comment]
I would recommend that you just open a PR. We can then decide if we want to incorporate your changes or not.

**Comment by karras** [comment]
@juler69 We're still interested in your enhancements. Care to still open a PR? If not I'll go ahead and close the issue.

Thanks! :)

**Comment by juler69** [comment]
Sure. I'm happy to do that. You might have to help me through the process.
I've never done one here before.

JJ

**Comment by karras** [comment]
Project archived
